version: "2"
services:

  audittrail-server:
    image: audittrail-server
    restart: always
    volumes:
      - ./serverdata:/app/bin/data
    expose: 
      - "3000"
    environment:
      - ETHNODE=http://172.30.0.1:8000/
      - BTCNODE=172.30.0.1:8332
      - BTCRPCUSER=bitcoin
      - BTCRPCPASS=bitcoin
    networks:
      vpcbr:
        ipv4_address: 172.30.0.2

  audittrail-client:
    image: audittrail-client
    depends_on:
      - audittrail-server
    volumes:
      - ./clientdata:/app/bin/data
    restart: always
    expose: 
      - "3000"
    environment:
      - SERVER=http://audittrail-server:3000/
    networks:
      vpcbr:
        ipv4_address: 172.30.0.4
       

networks:    
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24
          gateway: 172.30.0.1
